### ISSUE TITLE
Routing Issue

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-django-file-manager#4]
Hello @mominur-helios 

The routing needs to be like segments, not get parameters:

> Current routing:

`http://127.0.0.1:8000/file-manager/?directory=dir1`

> Expected routing:

`http://127.0.0.1:8000/file-manager/dir1`

This is important because we can have an arbitrary DIR depth and `dir1` can exist in different parts of the tree. 

Please take a look. 
TY!

**Comment by app-generator** [comment]
Hello @mominur-helios 

The new routing works, but I see a small issue when the user access the 2nd level directories:

- `Level1` -> OK
  - http://localhost:8000/file-manager/project2/
- `Level2` works but the link is not clean. Has that `%5C` between the segments
  - `http://localhost:8000/file-manager/project1%5Cdir1/`

The `Level2` URL needs to be:

`http://localhost:8000/file-manager/project/dir1/`

Please take a look.
TY!

**Comment by ghost** [comment]
Actually I'm using `linux` and here in my machine everything is working fine that's why I can't figure out what's the actual issue is. Anyway I'll try to fix it now @app-generator 

![Screenshot from 2023-07-04 12-05-15](https://github.com/app-generator/sample-django-file-manager/assets/101915710/1995152e-e28b-4233-94d4-d5a44c5b0d72)

**Comment by app-generator** [comment]
Validated. Closing
